### ISSUE TITLE
Naming of repo

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#17]
This repo name is going to be confusing.. what else could we come up with that expresses it better?

Yes I know I had something to do with finding the name originally.

**Comment by LucasRoesler** [comment]
Looking around the community `openfaas-operator`, `openfaas-controller`, and `openfaas-crd` seem like the natural choices.

Examples:
- https://github.com/coreos/prometheus-operator
- https://github.com/coreos/etcd-operator
- https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
- https://github.com/upmc-enterprises/kong-operator 
- https://github.com/caicloud/kubeflow-controller
- https://github.com/bitnami-labs/helm-crd

It seems like operator is pretty popular and has less conflicting SEO with something like controller.

Per CoreOS, which I think _defined_ the operator pattern, https://coreos.com/operators/

> An Operator is a method of packaging, deploying and managing a Kubernetes application. A Kubernetes application is an application that is both deployed on Kubernetes and managed using the Kubernetes APIs and kubectl tooling.

This project seems to fit.  So I would go with `openfaas-operator`

**Comment by stefanprodan** [comment]
I vote for `openfaas-operator` 🥇

**Comment by stefanprodan** [comment]
On today meeting with the core contributors we voted for `openfaas-operator` ✌️

**Comment by alexellis** [comment]
@stefanprodan please start to make changes for CI / namespaces etc so that the rename of the repo goes smoothly. Tell me when you want me to action that.

**Comment by alexellis** [comment]
Thanks for the input @LucasRoesler
