### ISSUE TITLE
Regenerate code / rename for openfaas-operator

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#18]
## Task

Regenerate code / rename for openfaas-operator

Also change domain name to openfaaas.com

Relates to #17 

Suggested by @stefanprodan

**Comment by alexellis** [comment]
@stefanprodan what is the update on this issue? Can it be closed yet?

**Comment by alexellis** [comment]
Why beta and not alpha 2?

**Comment by stefanprodan** [comment]
We discussed this on Slack, but if you want to use `v1alpha2` I'm ok with it.

**Comment by alexellis** [comment]
Yes I thought you were asking about the deployment version for Kubernetes and not the version of the operator.
