### ISSUE TITLE
Add the Operator to OpenFaaS Helm chart

### ISSUE THREAD

**Issue by stefanprodan** [openfaas-incubator/openfaas-operator#24]
We should add the Operator as a optional replacement of faas-netes into the Helm chart.

For this to happen we need to:
- [x] merge PR #23 
- [x] rename the CRD from `functions.o6s.io` to `functions.openfaas.com`
- [x] change the Operator code with the above naming #18

**Comment by alexellis** [comment]
LGTM

**Comment by alexellis** [comment]
I know you've been busy, this was raised around a month ago. Do you have an ETA @stefanprodan or do you need someone else to pick this up?

**Comment by stefanprodan** [comment]
I've made a PR here https://github.com/openfaas/faas-netes/pull/227 please give it a run
