### ISSUE TITLE
One bad function deployment causes strange behaviour

### ISSUE THREAD

**Issue by burtonr** [openfaas-incubator/openfaas-operator#41]
When deploying a function goes bad (for example: the image cannot be pulled), the Operator continuously throws an error. 

* The UI is blank
* `faas list` shows a 500 error

No functions are available or visible in the UI. It appears that nothing is deployed

Running `faas list` shows a 500 error
```
Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 500
```
The `faas invoke` still works as expected.

The issue _appears_ to be here: https://github.com/openfaas-incubator/openfaas-operator/blob/master/pkg/server/list.go#L30

Where `return` should be `continue`... I think.

The Operator logs are then filled with the repeating error:
```
1 list.go:30] Function listing getReplicas error: deployments.apps "bad-function" not found
```

I can resolve it by deleting the bad function using either `faas rm` or `kubectl delete -n openfaas-fn functions/bad-function`

**Comment by alexellis** [comment]
Please provide an example of a "bad" function for testing the fix.
