### ISSUE TITLE
Node Selector for Functions

### ISSUE THREAD

**Issue by insertjokehere** [openfaas-incubator/openfaas-operator#45]
Some of the functions that I am trying to run on OpenFaaS can only run on certain nodes in my cluster. For 'normal' workloads I would use a nodeSelector to ensure the pods get scheduled in the right place, but it doesn't seem to be possible to do this with the Function CRD

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by insertjokehere** [comment]
Doh! I looked at that file as well. Thanks

**Comment by alexellis** [comment]
Derek lock

**Comment by alexellis** [comment]
Glad we could help 😄
