### ISSUE TITLE
Deployments keep being updated when docker registry secret is provided

### ISSUE THREAD

**Issue by def1oyd** [openfaas-incubator/openfaas-operator#47]
I am on openfaas-operator 0.8.6 and I am deploying a function which its image is in a private registry.

I followed https://docs.openfaas.com/deployment/kubernetes/#create-an-image-pull-secret to provide the registry secret in my `stack.yml`. The `faas-cli deploy` had been accepted, and the deployment was created successfully in Kubernetes.

But I found that there were lots of exited Pods of this function, and the Pods got terminated and recreated again and again, very frequently. I checked the log of the operator, here is what I got

```
Function my-func secrets have changed
Updating deployment for my-func
Function my-func secrets have changed
Updating deployment for my-func
Function my-func secrets have changed
Updating deployment for my-func
Function my-func secrets have changed
Updating deployment for my-func
...
```

The operator was looping that 2 lines (`Function...; Updating...`) all the time, with a short interval. Obviously the deployment kept being updated, leading to the pods' terminations and recreations.

The first line of log comes from https://github.com/openfaas-incubator/openfaas-operator/blob/0.8.6/pkg/controller/deployment.go#L234

And the second line comes from https://github.com/openfaas-incubator/openfaas-operator/blob/0.8.6/pkg/controller/controller.go#L316 

Behind the first line, there is a checking if the secrets between the function and the deployment are equal, by comparing the slice `function.Spec.Secrets` and the slice built by `deployment.Spec.Template.Spec.Volumes[n].Projected.Sources.Secret.Name`

In this case,

* This checking failed
* The log `Function my-func secrets have changed` (first line) was printed
* `deploymentNeedsUpdate` returned `true`
* The log `Updating deployment for my-func` (second line) was printed
* Deployment was updated

So I did the below to see why the checking failed.

First I inspected the function
```bash
$ kubectl -n func get functions my-func -o yaml
```
I found
```
  secrets:
  - my-registry-secret
```

The I inspected the deployment
```bash
kubectl -n func get deployment my-func -o yaml
```
I found
```
      imagePullSecrets:
      - name: my-registry-secret
```
But I didn't find any `volumes`, and this is the problem.

According to https://github.com/openfaas-incubator/openfaas-operator/blob/0.8.6/pkg/controller/secrets.go#L31, if the secret type is `corev1.SecretTypeDockercfg` or `corev1.SecretTypeDockerConfigJson`, the secret will be appended to `deployment.Spec.Template.Spec.ImagePullSecrets`, and nothing for `deployment.Spec.Template.Spec.Volumes`

Here my `my-registry-secret` got appended to `imagePullSecrets` in the deployment, causing the absence of `volumes`, this produced non-empty `function.Spec.Secrets` (with 1 item `my-registry-secret`), and an empty `deployment.Spec.Template.Spec.Volumes`, leading to the checking failure.

I think this problem will exist as long as you have registry secret provided in the `stack.yml`, no matter you have application secret or not. The registry secret will be always in `function.Spec.Secrets`, and always not in `deployment.Spec.Template.Spec.Volumes`, the checking will always fail.

I have added the following snippet before https://github.com/openfaas-incubator/openfaas-operator/blob/0.8.6/pkg/controller/deployment.go#L233 to remove all the ImagePullSecrets, and so far it is working.

```go
	var secrets []string
	secrets = append(secrets, function.Spec.Secrets...)
	if len(secrets) > 0 && len(deployment.Spec.Template.Spec.ImagePullSecrets) > 0 {
		for i := len(secrets) - 1; i >= 0; i-- {
			for _, s := range deployment.Spec.Template.Spec.ImagePullSecrets {
				if s.Name == secrets[i] {
					secrets = append(secrets[:i], secrets[i+1:]...)
					break
				}
			}
		}
	}

	if secretsNotEqual(secrets, deployment.Spec.Template.Spec.Volumes) {
		glog.V(2).Infof("Function %s secrets have changed",
			function.Spec.Name)
		needsUpdate = true
	}
```

**Comment by def1oyd** [comment]
Thanks for the replies!

I haven't tried faas-netes, but I think it will work, because in this case it is the operator doing the checkings, and reacting to the results. Here the operator keeps updating the deployment as a result to the checking failures.

faas-netes does not check the Kubernetes resources and react to the result, so I think it will be fine.

Currently I am using a container built with the piece of code I mentioned at the last of my post as a workaround, so far it is working very well for my situation - providing registry secret via the `secrets` section in `stack.yml`.

**Comment by LucasRoesler** [comment]
After spending some time on it, i think the simplest and correct approach is to just check both image pull secrets and the projected secrets each time, like this

```go
// check if either of the projected function secrets or image pull secrets has been updated (added or removed)
func secretsNotEqual(secrets []string, volumes []corev1.Volume, imagePullSecrets []corev1.LocalObjectReference) bool {
	sources := []string{}
	for _, s := range imagePullSecrets {
		sources = append(sources, s.Name)
	}

	for _, s := range volumes[0].Projected.Sources {
		if s.Secret != nil {
			sources = append(sources, s.Secret.Name)
		}
	}

	sort.Strings(secrets)
	sort.Strings(sources)

	return strArrayNotEqual(secrets, sources)
}
```

This still wont cover the case where another component has modified the secrets or image pull secrets lists, but I am not sure we can easily detect that.

**Comment by LucasRoesler** [comment]
If we really want to check that the `Function` spec used to create the `Deployment` has changed, we probably need to embed the `Function` spec as an annotation on the `Deployment` and compare with that.

What are the situations where the `Function` object changes but the `Deployment` doesn't?

**Comment by stefanprodan** [comment]
@LucasRoesler embedding the function definition in the deployment annotation seems like the right approach to me. On every update event we can compare the two objects with `github.com/google/go-cmp/cmp` and detect changes in a reliable manner.
