### ISSUE TITLE
Fix validation of FunctionResources

### ISSUE THREAD

**Issue by bartsmykla** [openfaas-incubator/openfaas-operator#54]
OpenFaaS Cloud when deploying function is not using CPU limit, and when it's not provided it's send as empty string, which is failing validation with error: `spec.limits.cpu in body should match '^[0-9]+(m)'`
## Expected Behaviour

When function is being deployed without resources limits/requests it should validate correctly.

## Current Behaviour
When we are trying to deploy function without cpu/memory limit, validation is failing and function is not deployed.

## Possible Solution
Adding `omitempty` to cpu and memory https://github.com/openfaas-incubator/openfaas-operator/blob/master/pkg/apis/openfaas/v1alpha2/types.go#L38

## Your Environment
`openfaas-operator:0.8.9`

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by stefanprodan** [comment]
Deploying with limits at all should work? Did you test this change? I would test it without limits, only with cpu limit and only with memory limit.

**Comment by bartsmykla** [comment]
@stefanprodan I'm testing it now

**Comment by bartsmykla** [comment]
@stefanprodan I have tested it and without limits it's fine

**Comment by stefanprodan** [comment]
Great

**Comment by bartsmykla** [comment]
I have created Pull Request for that (https://github.com/openfaas-incubator/openfaas-operator/pull/55) but I need to test it tomorrow morning. My tests were:
- deploying function without limits
- deploying function with limit only for CPU
- deploying function with limit only for memory
- deploying function with limits for CPU and memory
If anyone wants to test it before me feel free to do so. :-)

**Comment by bartsmykla** [comment]
@alexellis @stefanprodan I tested the code and it fixes the problem. It took me a little bit longer, because I didn't know that before `omitempty` can't be space, so it didn't work at the beginning
