### ISSUE TITLE
Implement openfaas-provider secrets handler

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#69]
## Expected Behaviour

The faas-netes should expose the required secrets management APIs as specified in openfaas/faas#807

As per https://github.com/openfaas/faas-netes/issues/342 and 
https://github.com/openfaas/faas-provider/pull/12

## Current Behaviour

Secrets created via `kubectl` manually

**Comment by stefanprodan** [comment]
Derek assign: me
