### ISSUE TITLE
Return error messages from HTTP handlers in body

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#71]
## Expected Behaviour

Return error messages from HTTP handlers in body

## Current Behaviour

We just get the error codes

## Possible Solution

See the new secrets handler

https://github.com/openfaas-incubator/openfaas-operator/tree/master/pkg/server

**Comment by pcsx22** [comment]
This looks like a issue I can start with and get used to the contrubution procedure. I will start looking into it.

**Comment by alexellis** [comment]
Thank you
