### ISSUE TITLE
Feature: config option to force non-root user on functions

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#80]
## Expected Behaviour

As an OpenFaaS cluster operator, I should be able to set an env-var that states all functions should run as a non-root user i.e. > 10000.

## Current Behaviour

Possible but only with cumbersome Kubernetes extensions/policies.

## Possible Solution

Some variation of:

```
root_allowed=false
allow_root=false
runasuser=true
```

## Steps to Reproduce (for bugs)

1. `faas-cli new --lang Dockerfiles`
2. Add `USER root` at end of file
3. Build / deploy
4. If the flag is "on" then this function _should_ be rejected 

## Context

Moving towards secure-by-default.

This needs replicating in faas-netes, or the work could be done there first given that #79 vendors packages from the faas-netes codebase.

**Comment by stefanprodan** [comment]
This is blocked by faas-nest types package, the env vars should be implemented there in the bootstrap config, released with sem ver and pulled into the operator with dep.

**Comment by alexellis** [comment]
@stefanprodan where is this today?

**Comment by stefanprodan** [comment]
We can close this since the security context code is now shared between faas-netes and the operator. Also the helm chart sets the same env vars for both controllers.

**Comment by alexellis** [comment]
Thanks
