### ISSUE TITLE
Problem with Azure AKS Kubernetes service - deployment object not created

### ISSUE THREAD

**Issue by Qolzam** [openfaas-incubator/openfaas-operator#84]
## Expected Behaviour

Using *faas-cli* or *.yaml* to create a function on K8S.
Running bellow command:
``` bash
kubectl get deploy -n openfaas-fn

```
 It should show deployment object for that function.

Opening OpenFaaS Portal, I should see *Ready* status in OpenFaaS Portal.
 
## Current Behaviour

Using *faas-cli* or *.yaml* to create a function on K8S.
Running bellow command:
``` bash
kubectl get deploy -n openfaas-fn

```
 It doesn't show any deployment object for the function in K8S.

Opening OpenFaaS Portal, OpenFaaS Portal show the function name but the status is *Not Ready*.

## Possible Solution

- No idea

## Steps to Reproduce (for bugs)

Following [article](https://medium.com/@qolzam/openfaas-multi-stage-with-istio-on-kubernetes-bf184d3b6955)

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker 18.09.6

* What version and distriubtion of Kubernetes are you using? 1.14.3

* Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu V18.04.1

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
> Steps to Reproduce (for bugs)

^ perhaps you can at least give something? How about this? https://docs.microsoft.com/en-us/azure/aks/openfaas

**Comment by alexellis** [comment]
@burtonr please could I ask you to try two scenarios?

1x cluster with faas-netes
1x cluster with the OpenFaaS Operator

(Switching between these two options is just a helm flag)

**Comment by alexellis** [comment]
```
kubectl get deploy -n openfaas-fn
```

I noticed in your Slack screenshot you weren't using `openfaas-fn` but something like `openfaas-stg`? Are you using non-standard namespaces? How are you configuring this?

**Comment by burtonr** [comment]
@alexellis and @Qolzam I was able to create 2 new clusters, and deploy functions to each of them (with `faas-cli`) Everything was working perfectly for me.

Created 2 new AKS Kubernetes clusters:
```
$ az aks create -n openfaas-aks1 -g OpenFaaS-RG -k 1.12.8 -c 1 --generate-ssh-keys
$ az aks create -n openfaas-aks2 -g OpenFaaS-RG -k 1.12.8 -c 1 --generate-ssh-keys
```
faas-netes was used for `openfaas-aks1` cluster via Helm, and the openfaas-operator was used for `openfaas-aks2` cluster by including the `--set operator.create=true` flag, again with Helm

Created functions using `faas-cli`:
```
# faas-netes function
$ faas new qolzam-1 --lang go
$ faas up -f qolzam-1.yml

# operator function
$ faas new qolzam-2 --lang go
$ faas up -f qolzam-2.yml
```

faas-netes:
```
$ kubectl get deploy -n openfaas-fn
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
qolzam-1   1         1         1            1           29m
$ kubectl -n openfaas-fn get functions
error: the server doesn't have a resource type "functions"
```


OpenFaaS Operator:
```
$ kubectl get deploy -n openfaas-fn
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
qolzam-2   1         1         1            1           2m7s
$ kubectl -n openfaas-fn get functions
NAME       AGE
qolzam-2   2m
```

**Comment by Qolzam** [comment]
@burtonr Thank you for testing and fast reply. 
@alexellis I have added details steps in an article ( I have been writing already an article).

Indeed, I have created another cluster and following steps in [article](https://medium.com/@qolzam/openfaas-multi-stage-with-istio-on-kubernetes-bf184d3b6955) everything is working well and I can deploy faas function with *faas-cli* or *.yaml* file. I am not sure if it is a problem from AKS. Maybe there is something wrong with my configuration.

My environment on AKS:
- 3 *B2s Standard nodes*
- each node has 8GB RAM and 2 VCPU
- Basic networking
- K8S version 1.13.5

Not sure if there is more information about environment. If you need more information please let me know.

Thanks a lot!

**Comment by stefanprodan** [comment]
@Qolzam from the print screens you posted on Slack your old cluster had Istio on it. Have you enabled global mTLS? If so maybe the operator couldn't reach the Kubernetes API if AKS doesn't use the upstream default domain `.cluster.local`.

**Comment by Qolzam** [comment]
@stefanprodan, thanks for asking but I am not using mLTS.

**Comment by Qolzam** [comment]
I got the problem. Some times I forget to create the secret before pushing the function, *operator* get stuck in mounting the secret and doesn't work any more.

**Comment by Qolzam** [comment]
Isn't any better way to see the error as I only see success message on deploying function from faas-cli. Also operator logs only showing that _Function replica reader error: deployment.apps "function_name" not found_?

**Comment by alexellis** [comment]
👍 glad you got this resolved.

Was the gateway auth secret missing?

Alex

**Comment by alexellis** [comment]
If we can make this better, I'm open to suggestions @Qolzam

**Comment by Qolzam** [comment]
> 👍 glad you got this resolved.
> 
> Was the gateway auth secret missing?
> 
> Alex

Thank you @alexellis . The function secret itself was missing. I deployed a function like `func1` which was missing the secret on K8S but I added that secret for `func1 stack.yml`. So when the function want to mount the secret for `func1` it can not find the secret in K8S.
