### ISSUE TITLE
Support issue

### ISSUE THREAD

**Issue by alexsorkin** [openfaas-incubator/openfaas-operator#89]
Function crd.yaml maybe be "applied" only once.
All subsequent attempt will fail with exception:

## Expected Behaviour

kubectl -n <namespace> apply -f function-crd.yaml
function <name> **created**

kubectl -n <namespace> apply -f function-crd.yaml
function <name> **updated**

## Current Behaviour
kubectl -n <namespace> apply -f function-crd.yaml
function <name> **created**

kubectl -n <namespace> apply -f function-crd.yaml
FieldValueInvalid, :Invalid value: 0x0: must be specified for an update,field:metadata.resourceVersion

## Possible Solution
The resourceVersion tag should be completely ignored, or re-generated on update.

## Steps to Reproduce (for bugs)
1. Apply function-crd first time
2. Apply function-crd second time ==> Failure

## Context
Basically all types of automated flows with OpenFaaS operator are impossible.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version:      18.03.1-ce

* What version and distriubtion of Kubernetes are you using? `kubectl version`
IBM ICP 3.1.1(+3.1.2,3.2.0)
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp", GitCommit:"7005f63141281462932b6cd61e10b1d2d0fe98b8", GitTreeState:"clean", BuildDate:"2018-09-21T05:09:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp", GitCommit:"7005f63141281462932b6cd61e10b1d2d0fe98b8", GitTreeState:"clean", BuildDate:"2018-09-21T05:09:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux RHEL-7.3

* Link to your project or a code example to reproduce issue:
Internal, Financial Institution.

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Calico

**Comment by alexellis** [comment]
Hi @alexsorkin 

Thank you for your interest in OpenFaaS.

I am sorry to see that you are having some frustration with the operator, but "Impossible to upgrade function" is not quite descriptive enough and I don't think your example is something we can use to reproduce your issue.

Please create a public git repo or some examples that we can make use of.

I'll ping someone in the community to review once you have provided above.

> If any user needs urgent help, they should consider reaching out to OpenFaaS Ltd via [sales@openfaas.com](mailto:sales@openfaas.com).

**Comment by stefanprodan** [comment]
There is no `function-crd.yaml` in this repository. Please use:

```
kubectl apply -f https://raw.githubusercontent.com/openfaas-incubator/openfaas-operator/master/artifacts/operator-crd.yaml
customresourcedefinition.apiextensions.k8s.io/functions.openfaas.com created

kubectl apply -f https://raw.githubusercontent.com/openfaas-incubator/openfaas-operator/master/artifacts/operator-crd.yaml
customresourcedefinition.apiextensions.k8s.io/functions.openfaas.com unchanged

kubectl apply -f https://raw.githubusercontent.com/openfaas-incubator/openfaas-operator/master/artifacts/operator-crd.yaml
customresourcedefinition.apiextensions.k8s.io/functions.openfaas.com unchanged

```

**Comment by alexsorkin** [comment]
Please try following on any function you have deployed, to reproduce the issue:

[root@icpmasterqa01 ~]# kubectl -n ops-fn get fn testing-function -o yaml | grep -v resourceVersion| kubectl -n ops-fn apply -f -
The functions "testing-function" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

**Comment by alexellis** [comment]
Can you share `function-crd.yaml` please?

**Comment by alexsorkin** [comment]
resourceVersion should never be specified for kubernetes object update:
e.g:

[root@icpmasterqa01 ~]# kubectl -n ops-fn get **deploy** testing-function -o yaml | grep -v resourceVersion| kubectl -n ops-fn apply -f -
deployment.extensions/testing-function configured

**Comment by alexellis** [comment]
Can you share function-crd.yaml please?

**Comment by alexsorkin** [comment]
> Can you share `function-crd.yaml` please?

apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openfaas.com/v1alpha2","kind":"Function","metadata":{"annotations":{},"creationTimestamp":"2019-09-05T15:12:29Z","generation":1,"labels":{"app":"testing-function","heritage":"tiller","k8s-app":"example","package-name":"core-testing-package"},"name":"testing-function","namespace":"ops-fn","resourceVersion":"67241273","selfLink":"/apis/openfaas.com/v1alpha2/namespaces/ops-fn/functions/testing-function","uid":"93d00453-cfef-11e9-af76-00505694242a"},"spec":{"annotations":{"com.openfaas.health.http.initialDelay":"10s","com.openfaas.health.http.path":"/healthz","com.openfaas.health.http.periodSeconds":"3s","com.openfaas.health.http.timeoutSeconds":"2s","deployer.menora.co.il/revision":"eefc02b1eeff44e3c97e1400349a02e1342a2510","example.menora.co.il/build-repo":"menora-core/testing-function","example.menora.co.il/build-tag":"opsint-105","example.menora.co.il/canary-route":"edc56093c3","example.menora.co.il/headless":"False","example.menora.co.il/replicas-max":"5","example.menora.co.il/replicas-min":"2","example.menora.co.il/revision":"edc56093c31720fdfafb9efdb1dba7e40da9ccfa","example.menora.co.il/scale-barrier":"60","example.menora.co.il/scale-factor":"0","example.menora.co.il/short-name":"testing-function"},"environment":{"NODE_TLS_REJECT_UNAUTHORIZED":"0","SERVERLESS_MONGO_ADDRESS":"mongodb://mongo-ops-0.ops-app:27017/test-db","SERVERLESS_NATS_ADDRESS":"nats://pubsub-ops.ops-app:4222","SERVERLESS_NODE_ENV":"production","SERVERLESS_REDIS_ADDRESS":"redis://redis-ops-0.ops-app:6379"},"image":"menora-core/testing-function@sha256:da748faea0d359794c6a9c5b47de78b3fd2706cce0f95ff346604e87aa0661f7","labels":{"app":"testing-function","com.openfaas.scale.factor":"0","com.openfaas.scale.max":"2","com.openfaas.scale.min":"2","heritage":"openfaas","k8s-app":"example","package-name":"core-testing-package"},"limits":{"cpu":"500m","memory":"128Mi"},"name":"testing-function","replicas":2,"requests":{"cpu":"20m","memory":"64Mi"},"secrets":[]}}
  creationTimestamp: 2019-09-05T15:12:29Z
  generation: 1
  labels:
    app: testing-function
    heritage: tiller
    k8s-app: example
    package-name: core-testing-package
  name: testing-function
  namespace: ops-fn
  resourceVersion: "67241635"
  selfLink: /apis/openfaas.com/v1alpha2/namespaces/ops-fn/functions/testing-function
  uid: 93d00453-cfef-11e9-af76-00505694242a
spec:
  annotations:
    com.openfaas.health.http.initialDelay: 10s
    com.openfaas.health.http.path: /healthz
    com.openfaas.health.http.periodSeconds: 3s
    com.openfaas.health.http.timeoutSeconds: 2s
  environment:
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    SERVERLESS_MONGO_ADDRESS: mongodb://mongo-ops-0.ops-app:27017/test-db
    SERVERLESS_NATS_ADDRESS: nats://pubsub-ops.ops-app:4222
    SERVERLESS_NODE_ENV: production
    SERVERLESS_REDIS_ADDRESS: redis://redis-ops-0.ops-app:6379
  image: menora-core/testing-function@sha256:da748faea0d359794c6a9c5b47de78b3fd2706cce0f95ff346604e87aa0661f7
  labels:
    app: testing-function
    com.openfaas.scale.factor: "0"
    com.openfaas.scale.max: "2"
    com.openfaas.scale.min: "2"
    heritage: openfaas
    k8s-app: example
    package-name: core-testing-package
  limits:
    cpu: 500m
    memory: 128Mi
  name: testing-function
  replicas: 2
  requests:
    cpu: 20m
    memory: 64Mi
  secrets: []

**Comment by stefanprodan** [comment]
This is how Kubernetes works, you can't just take an object with `kubectl get -oyaml` and apply it again.

Use `kubectl -n ops-fn get function testing-function -oyaml --export`

**Comment by LucasRoesler** [comment]
@alexsorkin the file you posted looks like it was generated from the kubectl response, for example `kubectl get Function foo --o yaml > function-crd.yaml`  In general, it is not possible to apply the yaml generated by the `kubectl` CLI because it contains immutable metadata.

Can you share how you generated the `function-crd.yaml`?

The `faas-cli` has a `faas-cli generate` command that is supposed to generate the correct CRD yaml, this output should be saved and can be safely reapplied.

**Comment by alexsorkin** [comment]
The original function.yaml:

apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  labels:
    app: testing-function
    heritage: tiller
    k8s-app: example
    package-name: core-testing-package
  name: testing-function
  namespace: ops-fn
spec:
  annotations:
    com.openfaas.health.http.initialDelay: 10s
    com.openfaas.health.http.path: /healthz
    com.openfaas.health.http.periodSeconds: 3s
    com.openfaas.health.http.timeoutSeconds: 2s
  environment:
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    SERVERLESS_MONGO_ADDRESS: mongodb://mongo-ops-0.ops-app:27017/test-db
    SERVERLESS_NATS_ADDRESS: nats://pubsub-ops.ops-app:4222
    SERVERLESS_NODE_ENV: production
    SERVERLESS_REDIS_ADDRESS: redis://redis-ops-0.ops-app:6379
  image: menora-core/testing-function@sha256:da748faea0d359794c6a9c5b47de78b3fd2706cce0f95ff346604e87aa0661f7
  labels:
    app: testing-function
    com.openfaas.scale.factor: "0"
    com.openfaas.scale.max: "2"
    com.openfaas.scale.min: "2"
    heritage: openfaas
    k8s-app: example
    package-name: core-testing-package
  limits:
    cpu: 500m
    memory: 128Mi
  name: testing-function
  replicas: 2
  requests:
    cpu: 20m
    memory: 64Mi
  secrets: []

I can't apply it while there is same function deployed:
[root@icpmasterqa01 ~]# echo "apiVersion: openfaas.com/v1alpha2
> kind: Function
> metadata:
>   labels:
>     app: testing-function
>     heritage: tiller
>     k8s-app: example
>     package-name: core-testing-package
>   name: testing-function
>   namespace: ops-fn
> spec:
>   annotations:
>     com.openfaas.health.http.initialDelay: 10s
>     com.openfaas.health.http.path: /healthz
>     com.openfaas.health.http.periodSeconds: 3s
>     com.openfaas.health.http.timeoutSeconds: 2s
>   environment:
>     NODE_TLS_REJECT_UNAUTHORIZED: "0"
>     SERVERLESS_MONGO_ADDRESS: mongodb://mongo-ops-0.ops-app:27017/test-db
>     SERVERLESS_NATS_ADDRESS: nats://pubsub-ops.ops-app:4222
>     SERVERLESS_NODE_ENV: production
>     SERVERLESS_REDIS_ADDRESS: redis://redis-ops-0.ops-app:6379
>   image: menora-core/testing-function@sha256:da748faea0d359794c6a9c5b47de78b3fd2706cce0f95ff346604e87aa0661f7
>   labels:
>     app: testing-function
>     com.openfaas.scale.factor: "0"
>     com.openfaas.scale.max: "2"
>     com.openfaas.scale.min: "2"
>     heritage: openfaas
>     k8s-app: example
>     package-name: core-testing-package
>   limits:
>     cpu: 500m
>     memory: 128Mi
>   name: testing-function
>   replicas: 2
>   requests:
>     cpu: 20m
>     memory: 64Mi
>   secrets: []
> " | kubectl -n ops-fn apply -f -
The functions "testing-function" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

**Comment by alexsorkin** [comment]
And... no... in General...

kubectl -n ops-fn get fn testing-function -o yaml | grep -v resourceVersion| kubectl -n ops-fn apply -f -

Is working for ALL kubernetes object.

**Comment by alexsorkin** [comment]
Here is the issue:

```golang
oldFunc, _ := client.OpenfaasV1alpha2().Functions(namespace).Get(req.Service, opts)
		if oldFunc != nil {
			**newFunc.ResourceVersion = oldFunc.ResourceVersion**
		}
```

**Comment by alexsorkin** [comment]
Its unnecessary (breaking) to re-apply resourceVersion on to new Function instance.
`newFunc.ResourceVersion = oldFunc.ResourceVersion`

**Comment by alexellis** [comment]
Thanks for providing the additional information.

We'll consider it and let you know our take.
