### ISSUE TITLE
Remove comparison between the '.spec' fields so that resources can be re-synced

### ISSUE THREAD

**Issue by bmcstdio** [openfaas-incubator/openfaas-operator#95]
## Expected Behaviour

If syncing of my `Function` resource fails for some reason (failed to create the deployment/service, etc...), I am expecting the operator to try to sync it again after the configured [_resync period_](https://github.com/openfaas-incubator/openfaas-operator/blob/master/main.go#L100) elapses.

## Current Behaviour

The operator will _never_ retry syncing the `Function` resource again until I make a change to it's `.spec` field, due to [this](https://github.com/openfaas-incubator/openfaas-operator/blob/master/pkg/controller/controller.go#L136).

## Possible Solution

* Make the reconciliation logic idempotent (in case it already isn't).
* Remove the comparison of the `.spec` fields altogether, and let the operator enqueue the function for processing (as, as a side note, [`kubernetes/sample-controller`](https://github.com/kubernetes/sample-controller/blob/master/controller.go#L118-L120) advocates).

## Steps to Reproduce (for bugs)

1. Create a `Function` resource that for some reason doesn't get correctly synced (as described above).
2. Tail the logs of the operator and observe that it won't try to sync the `Function` ever again.
3. Make a change to the `Function` resource's annotations and observe that it is not synced.
4. Make a change to the `Function` resource's `.spec.` field and observe that is is indeed synced.

## Context

I am trying to replace `faas-netes` with the OpenFaaS operator, and, during my evaluation, creation of a `Deployment` resource for a function failed (as described in #94). In this situation, and as mentioned above, I am expecting the operator to continue trying to sync the `Function` resource so that it is eventually able to materialize it _without human interaction_.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

N/A

* What version and distriubtion of Kubernetes are you using? `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS 10.14.6

* Link to your project or a code example to reproduce issue:

N/A

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

https://github.com/aws/amazon-vpc-cni-k8s

**Comment by bmcstdio** [comment]
To give some more context, this kind of prevents a pipeline based on [Flux](https://fluxcd.io/) (and possibly, but not necessarily, [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets)) from working without human interaction, because when the `Function` resource is created the `Secrets` resources it requires may not exist:

```
E1019 12:18:31.892642       1 controller.go:224] error syncing 'openfaas-fn/my-function': secrets "my-function-private-key" not found
W1019 12:18:34.076541       1 list.go:39] Function listing getReplicas error: deployment.apps "my-function" not found
W1019 12:18:39.076543       1 list.go:39] Function listing getReplicas error: deployment.apps "my-function" not found
```

The operator won't perform any further reconciliation of the `Function` resource until I manually interact with it by changing something in the `.spec` field, which doesn't feel like a good UX at all.

**Comment by alexellis** [comment]
Could you provide a worked example or repo that we can use to reproduce the example?

Ideally it should be a few lines we can paste into KinD or minikube to see the error for ourselves.

**Comment by alexellis** [comment]
Requesting review from @stefanprodan, who I understand is a bit short on time at the moment. 

Did you have an example we can use @bmcstdio ?

**Comment by alexellis** [comment]
From Bruno - this change was needed for his use-case:

https://github.com/form3tech-oss/openfaas-operator/commit/c39b71548cca354150f6d870dcb87cd7fc20e637

**Comment by alexellis** [comment]
```
Alex Ellis: 
Should that behaviour be:
- Accepted / merged
- Put behind a non-default flag?
Or something else?

Stefan Prodan
I see no problem with it now that we use an annotation to prevent the mounts from being overwritten
```

@bmcstdio feel free to raise a PR.

**Comment by alexellis** [comment]
cc @LucasRoesler
