### ISSUE TITLE
Support multiple namespaces

### ISSUE THREAD

**Issue by bmcstdio** [openfaas-incubator/openfaas-operator#96]
## Expected Behaviour

`Function` resources created in multiple different namespaces are picked up and synced.

## Current Behaviour

Only functions in a single namespace (by default `openfaas-fn`) are picked up and synced.

## Possible Solution

* Make the operator watch resources across all Kubernetes namespaces.
* Introduce the required RBAC policies (cluster role and cluster role binding).
* Copy whatever `faas-netes` is doing as per https://github.com/openfaas/faas-netes/issues/511.

**Comment by bmcstdio** [comment]
@alexellis @stefanprodan I can start working on this if that's OK.

**Comment by alexellis** [comment]
@burtonr Have you seen #92, this seems like a dupe?

**Comment by bmcstdio** [comment]
> @burtonr Have you seen #92, this seems like a dupe?

It's @bmcstdio 🙂 From what I understood #92 deals only with the `/system/namespaces` endpoint. Granted there's more to multiple namespace support than that? 🙂

**Comment by alexellis** [comment]
IMHO it's the same thing, adding the endpoint and having it work means that any requisite work is also done.
